export const images = [
  "https://zensartech.top/assets/img/banner/1.png",
  "https://zensartech.top/assets/img/banner/3.png",
  "https://zensartech.top/assets/img/banner/2.png",
];

export const products = [
  {
    image: "/IMG/WhatsApp Image 2025-04-30 at 05.11.24_bd60e258.jpg",
    name: "YATI STARTER",
    prodText: "Start Smart, Grow Steadily.",
    prodIdeal: "Ideal For: Daily essentials and foundational support.",
    prodList: [
      "Local transportation coverage.",
      "Basic daily meal allowances.",
      "Access to community networking opportunities.",
    ],
    price1: "10",
    price2: "99",
  },
  {
    image: "/IMG/WhatsApp Image 2025-04-30 at 05.11.53_75aba231.jpg",
    name: "YATI HOPE EXPLORER",
    prodText: "Explore Limitless Possibilities.",
    prodIdeal: "Ideal For: Adventurers seeking affordable exploration.",
    prodList: [
      "Short-distance travel assistance (local/regional).",
      "Budget-friendly hotel accommodations.",
      "Curated local experience packages.",
    ],
    price1: "100",
    price2: "299",
  },
  {
    image: "/IMG/WhatsApp Image 2025-04-30 at 05.12.53_f34d84e9.jpg",
    name: "YATI BRIGHTER HORIZON",
    prodText: "Invest In Tomorrow, Today.",
    prodIdeal: "Ideal For: Professionals aiming for growth.",
    prodList: [
      "Expanded interstate travel support.",
      "Partial asset acquisition funding (e.g., tools, small equipment)",
      "Education fee subsidies.",
    ],
    price1: "300",
    price2: "599",
  },
  {
    image: "/IMG/WhatsApp Image 2025-04-30 at 05.13.48_57ab3a06.jpg",
    name: "YATI EMPOWER PASS",
    prodText: "Unlock Global Opportunities.",
    prodIdeal: "Ideal For: Ambitious individuals and entrepreneurs.",
    prodList: [
      "Premium domestic travel packages.",
      "Luxury vacation experiences (resorts, cruises).",
      "Fixed asset financing (property, vehicles).",
      "Priority access to Yaticare’s financial advisory network.",
    ],
    price1: "600",
    price2: "999",
  },
  {
    image: "/IMG/WhatsApp Image 2025-04-30 at 05.14.41_8ea10062.jpg",
    name: "YATI ELITE STARS",
    prodText: "Live Luxuriously, Thrive Endlessly.",
    prodIdeal:
      "Ideal For: High-net-worth individuals and lifestyle enthusiasts.",
    prodList: [
      "Premium and quality healthcare packages (global medical coverage).",
      "International travel concierge (bespoke itineraries).",
      "Custom car project support (imports, modifications).",
      "Exclusive networking events.",
    ],
    price1: "1,000",
    price2: "2,999",
  },
  {
    image: "/IMG/WhatsApp Image 2025-04-30 at 05.15.12_35ea150a.jpg",
    name: "YATI DIAMOND",
    prodText: "Redefine Excellence, Craft Your Legacy.",
    prodIdeal: "Ideal For: Visionaries building legacies.",
    prodList: [
      "Ultimate Travel: Private jet charters, 5-star global stays, and personalized cultural tours.",
      "Asset Mastery: High-value assets (real estate, businesses).",
      "Legacy Planning: Tailored wealth management, generational trust funds, and philanthropy coordination.",
      "24/7 Concierge: Dedicated support for lifestyle, finance, and exclusive event access.",
    ],
    price1: "3,000",
    price2: "5,000",
  },
];

export const countries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic (Czechia)",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City (Holy See)",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
